**(SAND) GRU model -‘Open’, ‘EMA_7’**

In [27]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout
from keras import optimizers
import matplotlib.pyplot as plt
from keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics
from keras.models import Sequential
from keras.layers import LSTM, GRU, Dense, Dropout,Activation
from keras import optimizers
import numpy
import matplotlib.pyplot as plt
import pandas
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

In [28]:
sand = 'https://raw.githubusercontent.com/loguansiang/fyp/main/SAND%20fyp.csv'
# slp= 'https://raw.githubusercontent.com/loguansiang/fyp/main/SLP%20fyp.csv'
# mana = 'https://raw.githubusercontent.com/loguansiang/fyp/main/MANA%20fyp.csv'

df = pd.read_csv(sand)

In [29]:
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace = True)

In [30]:
df

                Open      High       Low     Close  Adj Close     Volume
Date
2020-08-14  0.086577  0.086577  0.059597  0.065645   0.065645  118988161
2020-08-15  0.066077  0.069509  0.048985  0.050964   0.050964   36213441
2020-08-16  0.051438  0.069508  0.048064  0.060847   0.060847   33023213
2020-08-17  0.060847  0.065073  0.052525  0.053999   0.053999   11686493
2020-08-18  0.053784  0.060990  0.050675  0.051700   0.051700    7401293
...              ...       ...       ...       ...        ...        ...
2022-04-13  2.781983  2.886945  2.751847  2.869923   2.869923  321784424
2022-04-14  2.869366  2.916186  2.714203  2.780882   2.780882  349909147
2022-04-15  2.781060  2.820187  2.755915  2.803639   2.803639  189256519
2022-04-16  2.803614  2.901280  2.777383  2.822680   2.822680  234480315
2022-04-17  2.820111  2.820111  2.781153  2.790278   2.790278  176793328

[612 rows x 6 columns]

In [31]:
pip install ta

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: ta in /usr/local/lib/python3.7/dist-packages (0.10.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from ta) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from ta) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2022.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->ta) (1.15.0)

In [32]:
import pandas as pd
import ta
from ta import add_all_ta_features
from ta.utils import dropna

In [33]:
df['Pre_Close'] = df['Close'].shift(+1)
df[('H-L')] = df['High'] - df['Low']
df[('0-C')]= df['Open'] - df['Close']
df['SMA_7'] = df.Close.rolling(7, min_periods=1).mean()
df['rsi_7']=ta.momentum.rsi(df.Close,window=7)
#df['MACD'] = ta.trend.macd_diff(df.Close)
df['EMA_7']= df['Close'].ewm(span=7).mean()
df = df.drop(columns=['Adj Close'])
df.dropna(inplace= True)
df

,Open,High,Low,Close,Volume,Pre_Close,H-L,0-C,SMA_7,rsi_7,EMA_7
Date,,,,,,,,,,,
2020-08-20,0.052095,0.057325,0.050800,0.053648,7332475,0.052095,0.006525,-0.001553,0.055557,36.094661,0.054128
2020-08-21,0.053644,0.053738,0.044235,0.044235,5121097,0.053648,0.009503,0.009409,0.052498,23.308807,0.051380
2020-08-22,0.044395,0.049011,0.040692,0.046011,4347394,0.044235,0.008319,-0.001616,0.051791,28.856159,0.049928
2020-08-23,0.045990,0.048237,0.041965,0.044007,3114426,0.046011,0.006272,0.001983,0.049385,26.347291,0.048360
2020-08-24,0.043902,0.053543,0.042178,0.051299,7868186,0.044007,0.011365,-0.007397,0.048999,46.203257,0.049127
...,...,...,...,...,...,...,...,...,...,...,...
2022-04-13,2.781983,2.886945,2.751847,2.869923,321784424,2.782421,0.135098,-0.087940,2.886363,40.236566,2.909637
2022-04-14,2.869366,2.916186,2.714203,2.780882,349909147,2.869923,0.201983,0.088484,2.843185,36.188051,2.877448
2022-04-15,2.781060,2.820187,2.755915,2.803639,189256519,2.780882,0.064272,-0.022579,2.829312,38.046757,2.858996
2022-04-16,2.803614,2.901280,2.777383,2.822680,234480315,2.803639,0.123897,-0.019066,2.803156,39.759602,2.849917
2022-04-17,2.820111,2.820111,2.781153,2.790278,176793328,2.822680,0.038958,0.029833,2.788510,37.690803,2.835007

In [34]:
def data_prep(dataset, target, data_start, data_end, look_back, horizon):
    dataX,dataY = [],[]
    data_start = data_start + look_back
    if data_end is None:
        data_end = len(dataset) - horizon

    for i in range(data_start, data_end):
        a = range(i-look_back, i)
        dataX.append(dataset[a])

        b = range(i+1, i+1+horizon)
        dataY.append(target[b])
    return np.array(dataX), np.array(dataY)

In [35]:
X_scaler = MinMaxScaler()
Y_scaler = MinMaxScaler()
# X_data = X_scaler.fit_transform(df[['Open', 'High', 'Low','Volume','H-L',	'0-C','SMA_7','rsi_7','EMA_7']])//experiment4
X_data = X_scaler.fit_transform(df[['Open','High','Low','Volume','Pre_Close','H-L','0-C','SMA_7','rsi_7','EMA_7']])
Y_data = Y_scaler.fit_transform(df[['Close']])

##['Open', 'High', 'Low','Volume']
##['H-L',	'0-C','SMA_7','rsi_7','EMA_7']

In [36]:
##TRAIN_SPLIT = int(len(df) * 0.8)
look_back = 10
horizon = 10
train_split = int(len(df) * 0.8)
x_train, y_train = data_prep(X_data, Y_data, 0, train_split, look_back, horizon)
x_vali, y_vali = data_prep(X_data, Y_data, train_split, None, look_back, horizon)

In [37]:
# x_train

In [38]:
print ('Multiple window of past history\n')
print(x_train[0])
print ('\n Target horizon\n')
print (y_train[0])

Multiple window of past history

[[2.83694734e-03 3.03201955e-03 3.16017951e-03 4.25735345e-04
  2.54128088e-03 1.91371395e-03 6.35115494e-01 3.03411982e-03
  2.83541781e-01 3.01666711e-03]
 [3.04350110e-03 2.60551547e-03 2.21115712e-03 2.26069081e-04
  2.72679415e-03 3.00256381e-03 6.41058378e-01 2.60118256e-03
  1.30173805e-01 2.60212252e-03]
 [1.81017909e-03 2.04346228e-03 1.69898860e-03 1.56211107e-04
  1.60236635e-03 2.56965641e-03 6.35081339e-01 2.50102663e-03
  1.96715019e-01 2.38325056e-03]
 [2.02286680e-03 1.95143157e-03 1.88301076e-03 4.48858994e-05
  1.81451803e-03 1.82120924e-03 6.37032483e-01 2.16050054e-03
  1.66620823e-01 2.14663960e-03]
 [1.74443925e-03 2.58232944e-03 1.91380159e-03 4.74104920e-04
  1.57513066e-03 3.68336919e-03 6.31947257e-01 2.10590313e-03
  4.04795690e-01 2.26235884e-03]
 [2.67693150e-03 2.97506515e-03 2.43290889e-03 2.91205679e-04
  2.44619488e-03 3.57806739e-03 6.37483539e-01 2.03270215e-03
  3.37228304e-01 2.22158780e-03]
 [2.30156103e-03 3.20668766e-03 2.62892935e-03 5.16636406e-04
  2.06166996e-03 3.79452109e-03 6.30524695e-01 2.15415107e-03
  5.56005386e-01 2.57865429e-03]
 [3.66729615e-03 5.14159175e-03 3.69012865e-03 2.89300352e-03
  3.25872626e-03 7.06033939e-03 6.27616140e-01 2.55978963e-03
  7.32889556e-01 3.44185820e-03]
 [5.78670583e-03 6.00244749e-03 5.82336908e-03 2.07498525e-03
  5.12305693e-03 4.31188930e-03 6.38437155e-01 3.07355129e-03
  6.46304998e-01 3.92704424e-03]
 [5.17891237e-03 5.06585071e-03 5.34285873e-03 7.81648200e-04
  4.63735382e-03 2.64717023e-03 6.34411802e-01 3.60937435e-03
  6.76467394e-01 4.39727132e-03]]

 Target horizon

[[0.0047021 ]
 [0.00347374]
 [0.00337472]
 [0.00161431]
 [0.00174523]
 [0.00080584]
 [0.00120685]
 [0.00084849]
 [0.0022731 ]
 [0.00209141]]

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px # to plot the time series plot
from sklearn import metrics # for the evalution
from sklearn.preprocessing import LabelEncoder,MinMaxScaler

import tensorflow as tf

In [40]:
batch_size = 32
buffer_size = 18

train_data = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_data = train_data.batch(batch_size).repeat()

val_data = tf.data.Dataset.from_tensor_slices((x_vali, y_vali))
val_data = val_data.batch(batch_size).repeat()

In [41]:
from keras.models import Model
from keras.layers import Input
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
# from keras.layers.merge import concatenate
import tensorflow as tf

In [42]:
x_train.shape[-2:]

(10, 10)

In [43]:

# define model
# import tensorflow as tf
# from tensorflow.keras import layers
# Set random seed for as reproducible results as possible
# tf.random.set_seed(7)
# cnn_model = Sequential()
# cnn_model.add(Conv1D(filters=32, kernel_size=1, activation='relu', input_shape=(x_train.shape[-2:])))
# cnn_model.add(Conv1D(filters=64, kernel_size=1))
# cnn_model.add(MaxPooling1D(pool_size=(1)))
# cnn_model.add(Conv1D(filters=128, kernel_size=1))
# cnn_model.add(Flatten())
# cnn_model.add(Dense(256,))
# cnn_model.add(Dropout(0.2))
# cnn_model.add(Dense(10))
# cnn_model.compile(optimizer='adam', loss='mse')
# cnn_model.summary()

In [44]:

import tensorflow as tf
from tensorflow.keras import layers

# Set random seed for as reproducible results as possible
tf.random.set_seed(7)

lstm_model = Sequential()
lstm_model.add(GRU(100,return_sequences=True,input_shape=(x_train.shape[-2:])))
lstm_model.add(Dense(20,activation='linear'))
lstm_model.add(GRU(50))
lstm_model.add(Dropout(0.2))
lstm_model.add(Dense(units=horizon,activation='linear'))
lstm_model.compile(loss='mean_squared_error', optimizer='adam')
lstm_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 gru_2 (GRU)                 (None, 10, 100)           33600

 dense_2 (Dense)             (None, 10, 20)            2020

 gru_3 (GRU)                 (None, 50)                10800

 dropout_1 (Dropout)         (None, 50)                0

 dense_3 (Dense)             (None, 10)                510

=================================================================
Total params: 46,930
Trainable params: 46,930
Non-trainable params: 0
_________________________________________________________________

In [45]:
#model_path = 'CNN_Multivariate.h5'
#early_stopings = tf.keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=10, verbose=1, mode='min')
#checkpoint =  tf.keras.callbacks.ModelCheckpoint(model_path, monitor='val_loss', save_best_only=True, mode='min', verbose=0)
#callbacks=[early_stopings,checkpoint]

In [ ]:
history = lstm_model.fit(train_data,epochs=50,steps_per_epoch=100,validation_data=val_data,validation_steps=50,verbose=1)#callback
##history = cnn_model.fit(train_data,epochs=50,steps_per_epoch=100,validation_data=val_data,validation_steps=50,verbose=1)

Epoch 1/50
100/100 [==============================] - 5s 17ms/step - loss: 0.0116 - val_loss: 0.0079
Epoch 2/50
100/100 [==============================] - 2s 17ms/step - loss: 0.0069 - val_loss: 0.0072
Epoch 3/50
100/100 [==============================] - 2s 20ms/step - loss: 0.0064 - val_loss: 0.0054
Epoch 4/50
100/100 [==============================] - 2s 22ms/step - loss: 0.0044 - val_loss: 0.0056
Epoch 5/50
100/100 [==============================] - 2s 20ms/step - loss: 0.0052 - val_loss: 0.0090
Epoch 6/50
100/100 [==============================] - 2s 21ms/step - loss: 0.0043 - val_loss: 0.0122
Epoch 7/50
100/100 [==============================] - 2s 22ms/step - loss: 0.0049 - val_loss: 0.0161
Epoch 8/50
100/100 [==============================] - 2s 20ms/step - loss: 0.0045 - val_loss: 0.0110
Epoch 9/50
100/100 [==============================] - 2s 23ms/step - loss: 0.0038 - val_loss: 0.0061
Epoch 10/50
100/100 [==============================] - 2s 21ms/step - loss: 0.0045 - val_loss: 0.0164
Epoch 11/50
100/100 [==============================] - 2s 20ms/step - loss: 0.0043 - val_loss: 0.0120
Epoch 12/50
100/100 [==============================] - 1s 13ms/step - loss: 0.0034 - val_loss: 0.0301
Epoch 13/50
100/100 [==============================] - 1s 11ms/step - loss: 0.0033 - val_loss: 0.0110
Epoch 14/50
100/100 [==============================] - 1s 10ms/step - loss: 0.0030 - val_loss: 0.0356
Epoch 15/50
100/100 [==============================] - 1s 10ms/step - loss: 0.0036 - val_loss: 0.0416
Epoch 16/50
100/100 [==============================] - 1s 11ms/step - loss: 0.0025 - val_loss: 0.0151
Epoch 17/50
100/100 [==============================] - 1s 10ms/step - loss: 0.0024 - val_loss: 0.0382
Epoch 18/50
100/100 [==============================] - 1s 11ms/step - loss: 0.0021 - val_loss: 0.0248
Epoch 19/50
100/100 [==============================] - 1s 11ms/step - loss: 0.0020 - val_loss: 0.0496
Epoch 20/50
100/100 [==============================] - 1s 11ms/step - loss: 0.0020 - val_loss: 0.0446
Epoch 21/50
100/100 [==============================] - 1s 11ms/step - loss: 0.0019 - val_loss: 0.0454
Epoch 22/50
100/100 [==============================] - 1s 11ms/step - loss: 0.0018 - val_loss: 0.0744
Epoch 23/50
100/100 [==============================] - 1s 11ms/step - loss: 0.0026 - val_loss: 0.0384
Epoch 24/50
100/100 [==============================] - 1s 11ms/step - loss: 0.0019 - val_loss: 0.0281
Epoch 25/50
 98/100 [============================>.] - ETA: 0s - loss: 0.0020

In [ ]:
plt.figure(figsize=(16,9))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train loss', 'validation loss'])
plt.show()

In [ ]:
df.columns

In [ ]:

##['open']


data_val = X_scaler.fit_transform(df[['Open','High','Low','Volume','Pre_Close','H-L','0-C','SMA_7','rsi_7','EMA_7']].tail(10))
val_rescaled = data_val.reshape(1, data_val.shape[0], data_val.shape[1])
pred=lstm_model.predict(val_rescaled)
pred_Inverse = Y_scaler.inverse_transform(pred)
pred_Inverse

In [ ]:
def timeseries_evaluation_metrics_func(y_true, y_pred):
    def mean_absolute_percentage_error(y_true, y_pred): 
        y_true, y_pred = np.array(y_true), np.array(y_pred)
        return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

    print('Evaluation metric results:-')
    print(f'MSE is : {metrics.mean_squared_error(y_true, y_pred)}')
    print(f'MAE is : {metrics.mean_absolute_error(y_true, y_pred)}')
    print(f'RMSE is : {np.sqrt(metrics.mean_squared_error(y_true, y_pred))}')
    print(f'MAPE is : {mean_absolute_percentage_error(y_true, y_pred)}')

In [ ]:
validate = (df[['Close']].tail(10))
timeseries_evaluation_metrics_func(validate['Close'],pred_Inverse[0])

In [ ]:
plt.figure(figsize=(16,9))
plt.plot( list(validate['Close']))
plt.plot( list(pred_Inverse[0]))
plt.title("Actual vs Predicted")
plt.ylabel("Close")
plt.legend(('Actual','predicted'))
plt.show()